import 'package:firebase_core/firebase_core.dart';

/// Placeholder Firebase options loaded from compile-time environment vars. Replace
/// with values generated by `flutterfire configure` for production.
FirebaseOptions get defaultFirebaseOptions => FirebaseOptions(
      apiKey: const String.fromEnvironment('FIREBASE_API_KEY', defaultValue: ''),
      appId: const String.fromEnvironment('FIREBASE_APP_ID', defaultValue: ''),
      messagingSenderId:
          const String.fromEnvironment('FIREBASE_MESSAGING_SENDER_ID', defaultValue: ''),
      projectId:
          const String.fromEnvironment('FIREBASE_PROJECT_ID', defaultValue: ''),
      authDomain: '',
      databaseURL: '',
      storageBucket: '',
    );